<a href="https://colab.research.google.com/github/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/blob/main/Data_prepration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1) Importing Libraries

In [84]:
import pandas as pd
# import polars as p
import numpy as np
import warnings
warnings.filterwarnings(action = "ignore")
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler

#2) Loading Dataset

In [85]:
data = pd.read_csv("https://raw.githubusercontent.com/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/main/dataset.csv")

In [86]:
# Previewing data
data.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD

**Looking at the above dataset our target variable is the column "data_value".**

#3) Data Description

In [87]:
data.describe()

,YearStart,YearEnd,Data_Value_Unit,Data_Value,Data_Value_Alt,Low_Confidence_Limit,High_Confidence_Limit,Sample_Size,LocationID
count,53392.000000,53392.000000,0.0,48346.000000,48346.000000,48346.000000,48346.000000,48346.00000,53392.000000
mean,2013.281465,2013.281465,NaN,31.156681,31.156681,26.892227,35.989997,3889.19286,30.282215
std,1.693300,1.693300,NaN,10.247033,10.247033,10.038584,11.205813,19829.42129,16.821318
min,2011.000000,2011.000000,NaN,0.900000,0.900000,0.300000,3.000000,50.00000,1.000000
25%,2012.000000,2012.000000,NaN,24.100000,24.100000,20.000000,28.200000,566.00000,17.000000
50%,2013.000000,2013.000000,NaN,30.700000,30.700000,26.450000,35.600000,1209.00000,30.000000
75%,2015.000000,2015.000000,NaN,37.000000,37.000000,32.900000,42.200000,2519.00000,44.000000
max,2016.000000,2016.000000,NaN,77.600000,77.600000,69.500000,87.700000,476876.00000,78.000000

In [88]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53392 entries, 0 to 53391
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   YearStart                   53392 non-null  int64
 1   YearEnd                     53392 non-null  int64
 2   LocationAbbr                53392 non-null  object
 3   LocationDesc                53392 non-null  object
 4   Datasource                  53392 non-null  object
 5   Class                       53392 non-null  object
 6   Topic                       53392 non-null  object
 7   Question                    53392 non-null  object
 8   Data_Value_Unit             0 non-null      float64
 9   Data_Value_Type             53392 non-null  object
 10  Data_Value                  48346 non-null  float64
 11  Data_Value_Alt              48346 non-null  float64
 12  Data_Value_Footnote_Symbol  5046 non-null   object
 13  Data_Value_Footnote         5046 non-null   object
 14  Low_Confidence_Limit        48346 non-null  float64
 15  High_Confidence_Limit       48346 non-null  float64
 16  Sample_Size                 48346 non-null  float64
 17  Total                       1907 non-null   object
 18  Age(years)                  11438 non-null  object
 19  Education                   7628 non-null   object
 20  Gender                      3814 non-null   object
 21  Income                      13349 non-null  object
 22  Race/Ethnicity              15256 non-null  object
 23  GeoLocation                 52384 non-null  object
 24  ClassID                     53392 non-null  object
 25  TopicID                     53392 non-null  object
 26  QuestionID                  53392 non-null  object
 27  DataValueTypeID             53392 non-null  object
 28  LocationID                  53392 non-null  int64
 29  StratificationCategory1     53392 non-null  object
 30  Stratification1             53392 non-null  object
 31  StratificationCategoryId1   53392 non-null  object
 32  StratificationID1           53392 non-null  object
dtypes: float64(6), int64(3), object(24)
memory usage: 13.4+ MB

In [89]:
data.shape

(53392, 33)

In [90]:
col = data.columns
col

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

#4) Selecting necessary columns

## 4.1) Selection of columns

**Selecting features which will help us to classify different stratification categories.**

Most of the predictive values are correlated to each other so we dropped those columns which have less important(Refer EDA file).

In [91]:
df = data[['YearEnd','LocationAbbr','Sample_Size','Age(years)','Education','Gender','Income','Race/Ethnicity','ClassID','QuestionID','StratificationCategory1','Stratification1','StratificationCategoryId1','StratificationID1','Total','Data_Value']]

In [92]:
#dropping columns
for i in df.columns:
  data = data.drop([i],1)

In [93]:
df

,YearEnd,LocationAbbr,Sample_Size,Age(years),Education,Gender,Income,Race/Ethnicity,ClassID,QuestionID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Total,Data_Value
0,2011,AL,7304.0,NaN,NaN,NaN,NaN,NaN,OWS,Q036,Total,Total,OVR,OVERALL,Total,32.0
1,2011,AL,2581.0,NaN,NaN,Male,NaN,NaN,OWS,Q036,Gender,Male,GEN,MALE,NaN,32.3
2,2011,AL,4723.0,NaN,NaN,Female,NaN,NaN,OWS,Q036,Gender,Female,GEN,FEMALE,NaN,31.8
3,2011,AL,1153.0,NaN,Less than high school,NaN,NaN,NaN,OWS,Q036,Education,Less than high school,EDU,EDUHS,NaN,33.6
4,2011,AL,2402.0,NaN,High school graduate,NaN,NaN,NaN,OWS,Q036,Education,High school graduate,EDU,EDUHSGRAD,NaN,32.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,VI,NaN,NaN,NaN,NaN,NaN,Asian,PA,Q047,Race/Ethnicity,Asian,RACE,RACEASN,NaN,NaN
53388,2016,VI,NaN,NaN,NaN,NaN,NaN,Hawaiian/Pacific Islander,PA,Q047,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI,NaN,NaN
53389,2016,VI,NaN,NaN,NaN,NaN,NaN,American Indian/Alaska Native,PA,Q047,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA,NaN,NaN
53390,2016,VI,NaN,NaN,NaN,NaN,NaN,2 or more races,PA,Q047,Race/Ethnicity,2 or more races,RACE,RACE2PLUS,NaN,NaN
53391,2016,VI,NaN,NaN,NaN,NaN,NaN,Other,PA,Q047,Race/Ethnicity,Other,RACE,RACEOTH,NaN,NaN

## 4.2) Reason for removing columns

*   'Low_Confidence_Limit' => It is the lower limit of our target variable. Closer to Data_value.
*   'High_Confidence_Limit' => It is the higher limit of our target variable. Closer to Data_value.

*   'Data_Value_Alt' => Closer to Data_value.
*   'YearEnd' => We have taken starting year. We will take either 'Yearstart' or 'Yearend. Otherwise predator will correlated.

Most of the variables are not relevant to the target variables.

#5) Data Standardization

##5.1) Standardizing column names

In [94]:
df.columns = df.columns.str.lower()
df.head()

,yearend,locationabbr,sample_size,age(years),education,gender,income,race/ethnicity,classid,questionid,stratificationcategory1,stratification1,stratificationcategoryid1,stratificationid1,total,data_value
0,2011,AL,7304.0,NaN,NaN,NaN,NaN,NaN,OWS,Q036,Total,Total,OVR,OVERALL,Total,32.0
1,2011,AL,2581.0,NaN,NaN,Male,NaN,NaN,OWS,Q036,Gender,Male,GEN,MALE,NaN,32.3
2,2011,AL,4723.0,NaN,NaN,Female,NaN,NaN,OWS,Q036,Gender,Female,GEN,FEMALE,NaN,31.8
3,2011,AL,1153.0,NaN,Less than high school,NaN,NaN,NaN,OWS,Q036,Education,Less than high school,EDU,EDUHS,NaN,33.6
4,2011,AL,2402.0,NaN,High school graduate,NaN,NaN,NaN,OWS,Q036,Education,High school graduate,EDU,EDUHSGRAD,NaN,32.8

##5.2) Optimizing data (Data partitioning)

In [95]:
distinct_values = df['stratificationcategoryid1'].unique()
distinct_values

array(['OVR', 'GEN', 'EDU', 'AGEYR', 'INC', 'RACE'], dtype=object)

**Made 6 different dataframes for each category.**

In [96]:
total = df[df['stratificationcategoryid1'] == 'OVR'] # total
gen = df[df['stratificationcategoryid1'] == 'GEN'] #gender
edu  = df[df['stratificationcategoryid1'] == 'EDU'] #Education
age = df[df['stratificationcategoryid1'] == 'AGEYR'] #Age Range of sample
inc  = df[df['stratificationcategoryid1'] == 'INC'] #income range
race = df[df['stratificationcategoryid1'] == 'RACE'] # race

##5.3) Size of each category dataframe

In [97]:
print(f'Shape of category Race/ethinicity is {race.shape}')
print(f'Shape of category Income range is {inc.shape}')
print(f'Shape of category Age range of sample is {age.shape}')
print(f'Shape of category Education is {edu.shape}')
print(f'Shape of category Gender is {gen.shape}')
print(f'Shape of category total is {total.shape}')

Shape of category Race/ethinicity is (15256, 16)
Shape of category Income range is (13349, 16)
Shape of category Age range of sample is (11438, 16)
Shape of category Education is (7628, 16)
Shape of category Gender is (3814, 16)
Shape of category total is (1907, 16)

#6) Looking for Null values

##6.1) For total dataframe

In [98]:
print(data.isnull().sum())

YearStart                         0
LocationDesc                      0
Datasource                        0
Class                             0
Topic                             0
Question                          0
Data_Value_Unit               53392
Data_Value_Type                   0
Data_Value_Alt                 5046
Data_Value_Footnote_Symbol    48346
Data_Value_Footnote           48346
Low_Confidence_Limit           5046
High_Confidence_Limit          5046
GeoLocation                    1008
TopicID                           0
DataValueTypeID                   0
LocationID                        0
dtype: int64

##6.2) Missing values (Category wise)

###6.2.1) Race

In [99]:
race.isnull().sum()

yearend                          0
locationabbr                     0
sample_size                   5046
age(years)                   15256
education                    15256
gender                       15256
income                       15256
race/ethnicity                   0
classid                          0
questionid                       0
stratificationcategory1          0
stratification1                  0
stratificationcategoryid1        0
stratificationid1                0
total                        15256
data_value                    5046
dtype: int64

  **For race, sample_size and data_value is also null so we will remove these.**

In [100]:
race= race.dropna(subset=['data_value'])

In [101]:
race.isnull().sum()

yearend                          0
locationabbr                     0
sample_size                      0
age(years)                   10210
education                    10210
gender                       10210
income                       10210
race/ethnicity                   0
classid                          0
questionid                       0
stratificationcategory1          0
stratification1                  0
stratificationcategoryid1        0
stratificationid1                0
total                        10210
data_value                       0
dtype: int64

###6.2.2) Income

In [102]:
inc.isnull().sum()

yearend                          0
locationabbr                     0
sample_size                      0
age(years)                   13349
education                    13349
gender                       13349
income                           0
race/ethnicity               13349
classid                          0
questionid                       0
stratificationcategory1          0
stratification1                  0
stratificationcategoryid1        0
stratificationid1                0
total                        13349
data_value                       0
dtype: int64

###6.2.3) Age

In [103]:
age.isnull().sum()

yearend                          0
locationabbr                     0
sample_size                      0
age(years)                       0
education                    11438
gender                       11438
income                       11438
race/ethnicity               11438
classid                          0
questionid                       0
stratificationcategory1          0
stratification1                  0
stratificationcategoryid1        0
stratificationid1                0
total                        11438
data_value                       0
dtype: int64

###6.2.4) Education

In [104]:
edu.isnull().sum()

yearend                         0
locationabbr                    0
sample_size                     0
age(years)                   7628
education                       0
gender                       7628
income                       7628
race/ethnicity               7628
classid                         0
questionid                      0
stratificationcategory1         0
stratification1                 0
stratificationcategoryid1       0
stratificationid1               0
total                        7628
data_value                      0
dtype: int64

### 6.2.5) Gender

In [105]:
gen.isnull().sum()

yearend                         0
locationabbr                    0
sample_size                     0
age(years)                   3814
education                    3814
gender                          0
income                       3814
race/ethnicity               3814
classid                         0
questionid                      0
stratificationcategory1         0
stratification1                 0
stratificationcategoryid1       0
stratificationid1               0
total                        3814
data_value                      0
dtype: int64

###6.2.6) Total

In [106]:
total.isnull().sum()

yearend                         0
locationabbr                    0
sample_size                     0
age(years)                   1907
education                    1907
gender                       1907
income                       1907
race/ethnicity               1907
classid                         0
questionid                      0
stratificationcategory1         0
stratification1                 0
stratificationcategoryid1       0
stratificationid1               0
total                           0
data_value                      0
dtype: int64

##6.3) Observation

1.From the above null values we know that for each category other cateregeries values(column) are null so we will remove those feature for particular dataframe

Eg. for race total category other categories(age, education, gender, income, race) are null.

2 . All the category values are also given in stratification column so we can also drop this column.

In [107]:
race.head()

,yearend,locationabbr,sample_size,age(years),education,gender,income,race/ethnicity,classid,questionid,stratificationcategory1,stratification1,stratificationcategoryid1,stratificationid1,total,data_value
20,2011,AL,5042.0,NaN,NaN,NaN,NaN,Non-Hispanic White,OWS,Q036,Race/Ethnicity,Non-Hispanic White,RACE,RACEWHT,NaN,29.8
21,2011,AL,1878.0,NaN,NaN,NaN,NaN,Non-Hispanic Black,OWS,Q036,Race/Ethnicity,Non-Hispanic Black,RACE,RACEBLK,NaN,40.1
22,2011,AL,115.0,NaN,NaN,NaN,NaN,Hispanic,OWS,Q036,Race/Ethnicity,Hispanic,RACE,RACEHIS,NaN,28.6
25,2011,AL,61.0,NaN,NaN,NaN,NaN,American Indian/Alaska Native,OWS,Q036,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA,NaN,32.9
26,2011,AL,58.0,NaN,NaN,NaN,NaN,2 or more races,OWS,Q036,Race/Ethnicity,2 or more races,RACE,RACE2PLUS,NaN,27.8

##6.4) Dropping Missing values
(According to the above observations)

In [108]:
columns_to_drop = ['race/ethnicity','income','age(years)','gender','education','total']
race.drop(columns=columns_to_drop, inplace=True)
columns_to_drop = ['income','race/ethnicity','age(years)','gender','education','total']
inc.drop(columns=columns_to_drop, inplace=True)
columns_to_drop = ['race/ethnicity','income','age(years)','gender','education','total']
age.drop(columns=columns_to_drop, inplace=True)
columns_to_drop = ['race/ethnicity','income','age(years)','gender','education','total']
edu.drop(columns=columns_to_drop, inplace=True)
columns_to_drop = ['race/ethnicity','income','age(years)','gender','education','total']
gen.drop(columns=columns_to_drop, inplace=True)
columns_to_drop = ['race/ethnicity','income','age(years)','gender','education','total']
total.drop(columns=columns_to_drop, inplace=True)

In [109]:
dataframes = [race,inc,age,edu,gen,total]

In [110]:
for i, df in enumerate(dataframes, start=1):
    null_count = df.isnull().sum().sum()
    print(f"Null values in df{i}: {null_count}")

Null values in df1: 0
Null values in df2: 0
Null values in df3: 0
Null values in df4: 0
Null values in df5: 0
Null values in df6: 0

**Now we don't have any null values in our datasets.**

#7) Preprocessing

## 7.1) Removing outliers for each dataframes

In [111]:
#creating function to remove outliers by using interquartile function
def remove_outliers(df):
    for col in df.select_dtypes(include=np.number).columns:
        q1 = df[col].quantile(0.25)
        q3 = df[col].quantile(0.75)
        iqr = q3 - q1
        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)
        df.drop(df[(df[col] < lower_bound) | (df[col] > upper_bound)].index, inplace=True)

In [112]:
for i in dataframes:
  remove_outliers(i)

## 7.2) Size of each category after removing outliers

In [113]:
print(f'Shape of category Race/ethinicity is {race.shape}')
print(f'Shape of category Income range is {inc.shape}')
print(f'Shape of category Age range of sample is {age.shape}')
print(f'Shape of category Education is {edu.shape}')
print(f'Shape of category Gender is {gen.shape}')
print(f'Shape of category total is {total.shape}')

Shape of category Race/ethinicity is (8253, 10)
Shape of category Income range is (12102, 10)
Shape of category Age range of sample is (10701, 10)
Shape of category Education is (7008, 10)
Shape of category Gender is (3525, 10)
Shape of category total is (1732, 10)

# 8) Feature Selection

## 8.1) Dropping correlated feature

In [114]:
race.head(3)

,yearend,locationabbr,sample_size,classid,questionid,stratificationcategory1,stratification1,stratificationcategoryid1,stratificationid1,data_value
21,2011,AL,1878.0,OWS,Q036,Race/Ethnicity,Non-Hispanic Black,RACE,RACEBLK,40.1
22,2011,AL,115.0,OWS,Q036,Race/Ethnicity,Hispanic,RACE,RACEHIS,28.6
25,2011,AL,61.0,OWS,Q036,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA,32.9

In [115]:
columns_to_drop = ['stratificationcategory1','stratification1','stratificationcategoryid1']
race = race.drop(columns=columns_to_drop)
inc = inc.drop(columns=columns_to_drop)
age = age.drop(columns=columns_to_drop)
edu = edu.drop(columns=columns_to_drop)
gen = gen.drop(columns=columns_to_drop)
total = total.drop(columns=columns_to_drop)

In [116]:
race

,yearend,locationabbr,sample_size,classid,questionid,stratificationid1,data_value
21,2011,AL,1878.0,OWS,Q036,RACEBLK,40.1
22,2011,AL,115.0,OWS,Q036,RACEHIS,28.6
25,2011,AL,61.0,OWS,Q036,RACENAA,32.9
26,2011,AL,58.0,OWS,Q036,RACE2PLUS,27.8
49,2011,AL,1878.0,OWS,Q037,RACEBLK,30.1
...,...,...,...,...,...,...,...
53334,2016,GU,511.0,PA,Q047,RACEHPI,34.6
53336,2016,GU,203.0,PA,Q047,RACE2PLUS,21.5
53384,2016,VI,154.0,PA,Q047,RACEWHT,18.3
53385,2016,VI,820.0,PA,Q047,RACEBLK,24.1
53386,2016,VI,178.0,PA,Q047,RACEHIS,30.3


1.stratificationcategory1, stratificationcategoryid1--> all the data is for income so we removed.

2.stratification1 ---> It is a income range and we already have stratificationid1 as abbrevation for this.

## 8.2) Encoding

In [117]:
print(race.dtypes)

yearend                int64
locationabbr          object
sample_size          float64
classid               object
questionid            object
stratificationid1     object
data_value           float64
dtype: object

###8.2.1) Label Encoding (for ordinal categorical data):
 Using label encoding when the categorical data have an inherent order or hierarchy.

In [118]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [119]:
le = LabelEncoder()
race['locationabbr'] = le.fit_transform(race["locationabbr"])
race['classid'] = le.fit_transform(race["classid"])
race['questionid'] = le.fit_transform(race["questionid"])

inc['locationabbr'] = le.fit_transform(inc["locationabbr"])
inc['classid'] = le.fit_transform(inc["classid"])
inc['questionid'] = le.fit_transform(inc["questionid"])

age['locationabbr'] = le.fit_transform(age["locationabbr"])
age['classid'] = le.fit_transform(age["classid"])
age['questionid'] = le.fit_transform(age["questionid"])

gen['locationabbr'] = le.fit_transform(gen["locationabbr"])
gen['classid'] = le.fit_transform(gen["classid"])
gen['questionid'] = le.fit_transform(gen["questionid"])

edu['locationabbr'] = le.fit_transform(edu["locationabbr"])
edu['classid'] = le.fit_transform(edu["classid"])
edu['questionid'] = le.fit_transform(edu["questionid"])

total['locationabbr'] = le.fit_transform(total["locationabbr"])
total['classid'] = le.fit_transform(total["classid"])
total['questionid'] = le.fit_transform(total["questionid"])

In [120]:
dataframe = [race,inc,age,gen,edu,total]

In [121]:
race

,yearend,locationabbr,sample_size,classid,questionid,stratificationid1,data_value
21,2011,1,1878.0,1,2,RACEBLK,40.1
22,2011,1,115.0,1,2,RACEHIS,28.6
25,2011,1,61.0,1,2,RACENAA,32.9
26,2011,1,58.0,1,2,RACE2PLUS,27.8
49,2011,1,1878.0,1,3,RACEBLK,30.1
...,...,...,...,...,...,...,...
53334,2016,11,511.0,2,8,RACEHPI,34.6
53336,2016,11,203.0,2,8,RACE2PLUS,21.5
53384,2016,48,154.0,2,8,RACEWHT,18.3
53385,2016,48,820.0,2,8,RACEBLK,24.1
53386,2016,48,178.0,2,8,RACEHIS,30.3

### 8.2.2) One-Hot Encoding (for nominal categorical data):
Using one-hot encoding when there is no specific order or hierarchy among the categories.

In [122]:
columns_to_drop = ['stratificationid1']
for i in range(len(dataframe)):
  dataframe[i] = dataframe[i].drop(columns=columns_to_drop)

In [123]:
# dataframe = [race,inc,age,gen,edu,total]

In [124]:
dataframe[0]

       yearend  locationabbr  sample_size  classid  questionid  data_value
21        2011             1       1878.0        1           2        40.1
22        2011             1        115.0        1           2        28.6
25        2011             1         61.0        1           2        32.9
26        2011             1         58.0        1           2        27.8
49        2011             1       1878.0        1           3        30.1
...        ...           ...          ...      ...         ...         ...
53334     2016            11        511.0        2           8        34.6
53336     2016            11        203.0        2           8        21.5
53384     2016            48        154.0        2           8        18.3
53385     2016            48        820.0        2           8        24.1
53386     2016            48        178.0        2           8        30.3

[8253 rows x 6 columns]

## 8.3) Saving files into csv

Saving each category dataframes into csv file for further process.

In [125]:
dataframes = [race, inc, age, edu, gen, total]
categories = ['race', 'income', 'age', 'education', 'gender', 'total']

In [128]:
for i, df in enumerate(dataframes):
    filename = f'{categories[i]}.csv'
    df.to_csv(filename, index=False)

In [129]:
dataframe[0]

       yearend  locationabbr  sample_size  classid  questionid  data_value
21        2011             1       1878.0        1           2        40.1
22        2011             1        115.0        1           2        28.6
25        2011             1         61.0        1           2        32.9
26        2011             1         58.0        1           2        27.8
49        2011             1       1878.0        1           3        30.1
...        ...           ...          ...      ...         ...         ...
53334     2016            11        511.0        2           8        34.6
53336     2016            11        203.0        2           8        21.5
53384     2016            48        154.0        2           8        18.3
53385     2016            48        820.0        2           8        24.1
53386     2016            48        178.0        2           8        30.3

[8253 rows x 6 columns]