<a href="https://colab.research.google.com/github/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/blob/BHOOMI_202218063/DM_PROJECT_FEATURE_SELECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
# import polars as p
import numpy as np
import warnings
warnings.filterwarnings(action = "ignore")


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.preprocessing import OneHotEncoder

from sklearn import preprocessing

from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split, cross_validate, cross_val_score, GridSearchCV
import math

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/main/dataset.csv")

In [3]:
data.shape

(53392, 33)

In [4]:
data

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Asian,RACE,RACEASN
53388,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI
53389,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA
53390,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
53391,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Other,RACE,RACEOTH

In [5]:
col = data.columns
col

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

## SELECTING FEATURES WHICH WILL HELP US TO CLASSIFY DIFFERENT STRATIFICATION CATEGORY.

### Most of the predictive values are correlated to each other so we dropped those columns which have less importance (Refer EDA file).

In [6]:
df = data[['YearEnd','LocationAbbr','Sample_Size','Age(years)','Education','Gender','Income','Race/Ethnicity','ClassID','Question','QuestionID','StratificationCategory1','Stratification1','StratificationCategoryId1','StratificationID1','Total','Data_Value', 'Low_Confidence_Limit', 'High_Confidence_Limit ']]

In [7]:
df

,YearEnd,LocationAbbr,Sample_Size,Age(years),Education,Gender,Income,Race/Ethnicity,ClassID,Question,QuestionID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Total,Data_Value,Low_Confidence_Limit,High_Confidence_Limit
0,2011,AL,7304.0,NaN,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Total,Total,OVR,OVERALL,Total,32.0,30.5,33.5
1,2011,AL,2581.0,NaN,NaN,Male,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Gender,Male,GEN,MALE,NaN,32.3,29.9,34.7
2,2011,AL,4723.0,NaN,NaN,Female,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Gender,Female,GEN,FEMALE,NaN,31.8,30.0,33.6
3,2011,AL,1153.0,NaN,Less than high school,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Education,Less than high school,EDU,EDUHS,NaN,33.6,29.9,37.6
4,2011,AL,2402.0,NaN,High school graduate,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Education,High school graduate,EDU,EDUHSGRAD,NaN,32.8,30.2,35.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,VI,NaN,NaN,NaN,NaN,NaN,Asian,PA,Percent of adults who engage in no leisure-tim...,Q047,Race/Ethnicity,Asian,RACE,RACEASN,NaN,NaN,NaN,NaN
53388,2016,VI,NaN,NaN,NaN,NaN,NaN,Hawaiian/Pacific Islander,PA,Percent of adults who engage in no leisure-tim...,Q047,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI,NaN,NaN,NaN,NaN
53389,2016,VI,NaN,NaN,NaN,NaN,NaN,American Indian/Alaska Native,PA,Percent of adults who engage in no leisure-tim...,Q047,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA,NaN,NaN,NaN,NaN
53390,2016,VI,NaN,NaN,NaN,NaN,NaN,2 or more races,PA,Percent of adults who engage in no leisure-tim...,Q047,Race/Ethnicity,2 or more races,RACE,RACE2PLUS,NaN,NaN,NaN,NaN
53391,2016,VI,NaN,NaN,NaN,NaN,NaN,Other,PA,Percent of adults who engage in no leisure-tim...,Q047,Race/Ethnicity,Other,RACE,RACEOTH,NaN,NaN,NaN,NaN

In [8]:
distinct_values = df['StratificationCategoryId1'].unique()
distinct_values

array(['OVR', 'GEN', 'EDU', 'AGEYR', 'INC', 'RACE'], dtype=object)

In [14]:
total = df[df['StratificationCategoryId1'] == 'OVR'] # total
gen = df[df['StratificationCategoryId1'] == 'GEN'] #gender
edu  = df[df['StratificationCategoryId1'] == 'EDU'] #Education
ageyr = df[df['StratificationCategoryId1'] == 'AGEYR'] #Age Range of sample
inc  = df[df['StratificationCategoryId1'] == 'INC'] #income range
race = df[df['StratificationCategoryId1'] == 'RACE'] # race

In [16]:
ageyr

,YearEnd,LocationAbbr,Sample_Size,Age(years),Education,Gender,Income,Race/Ethnicity,ClassID,Question,QuestionID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Total,Data_Value,Low_Confidence_Limit,High_Confidence_Limit
7,2011,AL,356.0,18 - 24,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Age (years),18 - 24,AGEYR,AGEYR1824,NaN,16.3,12.6,20.9
8,2011,AL,598.0,25 - 34,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Age (years),25 - 34,AGEYR,AGEYR2534,NaN,35.2,30.7,40.0
9,2011,AL,865.0,35 - 44,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Age (years),35 - 44,AGEYR,AGEYR3544,NaN,35.5,31.6,39.6
10,2011,AL,1288.0,45 - 54,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Age (years),45 - 54,AGEYR,AGEYR4554,NaN,38.0,34.5,41.5
11,2011,AL,1676.0,55 - 64,NaN,NaN,NaN,NaN,OWS,Percent of adults aged 18 years and older who ...,Q036,Age (years),55 - 64,AGEYR,AGEYR5564,NaN,36.4,33.4,39.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53372,2016,VI,110.0,25 - 34,NaN,NaN,NaN,NaN,PA,Percent of adults who engage in no leisure-tim...,Q047,Age (years),25 - 34,AGEYR,AGEYR2534,NaN,34.7,23.7,47.7
53373,2016,VI,99.0,35 - 44,NaN,NaN,NaN,NaN,PA,Percent of adults who engage in no leisure-tim...,Q047,Age (years),35 - 44,AGEYR,AGEYR3544,NaN,29.3,18.4,43.4
53374,2016,VI,232.0,45 - 54,NaN,NaN,NaN,NaN,PA,Percent of adults who engage in no leisure-tim...,Q047,Age (years),45 - 54,AGEYR,AGEYR4554,NaN,22.5,16.4,30.0
53375,2016,VI,321.0,55 - 64,NaN,NaN,NaN,NaN,PA,Percent of adults who engage in no leisure-tim...,Q047,Age (years),55 - 64,AGEYR,AGEYR5564,NaN,24.6,18.7,31.6
53376,2016,VI,450.0,65 or older,NaN,NaN,NaN,NaN,PA,Percent of adults who engage in no leisure-tim...,Q047,Age (years),65 or older,AGEYR,AGEYR65PLUS,NaN,23.9,18.9,29.8