<a href="https://colab.research.google.com/github/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/blob/JATAN_202218061/DM_PROJECT_FEATURE_SELECTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
# import polars as p
import numpy as np
import warnings
warnings.filterwarnings(action = "ignore")


import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import statsmodels.api as sm
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae
from sklearn.preprocessing import OneHotEncoder

from sklearn import preprocessing

from sklearn.metrics import mean_squared_error, mean_absolute_error

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import train_test_split, cross_validate, cross_val_score, GridSearchCV
import math

In [ ]:
data = pd.read_csv("https://raw.githubusercontent.com/Jatansahu/GOLDDIGGER_GROUP12_PROJECT_01/main/dataset.csv")

In [ ]:
data.shape

(53392, 33)

In [ ]:
data

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Total,Total,OVR,OVERALL
1,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Male,GEN,MALE
2,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Gender,Female,GEN,FEMALE
3,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,Less than high school,EDU,EDUHS
4,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,Value,...,"(32.84057112200048, -86.63186076199969)",OWS,OWS1,Q036,VALUE,1,Education,High school graduate,EDU,EDUHSGRAD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Asian,RACE,RACEASN
53388,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI
53389,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA
53390,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
53391,2016,2016,VI,Virgin Islands,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,NaN,Value,...,"(18.335765, -64.896335)",PA,PA1,Q047,VALUE,78,Race/Ethnicity,Other,RACE,RACEOTH

In [ ]:
col = data.columns
col

Index(['YearStart', 'YearEnd', 'LocationAbbr', 'LocationDesc', 'Datasource',
       'Class', 'Topic', 'Question', 'Data_Value_Unit', 'Data_Value_Type',
       'Data_Value', 'Data_Value_Alt', 'Data_Value_Footnote_Symbol',
       'Data_Value_Footnote', 'Low_Confidence_Limit', 'High_Confidence_Limit ',
       'Sample_Size', 'Total', 'Age(years)', 'Education', 'Gender', 'Income',
       'Race/Ethnicity', 'GeoLocation', 'ClassID', 'TopicID', 'QuestionID',
       'DataValueTypeID', 'LocationID', 'StratificationCategory1',
       'Stratification1', 'StratificationCategoryId1', 'StratificationID1'],
      dtype='object')

## SELECTING FEATURES WHICH WILL HELP US TO CLASSIFY DIFFERENT STRATIFICATION CATEGORY.

### Most of the predictive values are correlated to each other so we dropped those columns which have less important(Refer EDA file).

In [ ]:
df = data[['YearEnd','LocationAbbr','Sample_Size','Age(years)','Education','Gender','Income','Race/Ethnicity','ClassID','QuestionID','StratificationCategory1','Stratification1','StratificationCategoryId1','StratificationID1','Total','Data_Value']]

In [ ]:
df

,YearEnd,LocationAbbr,Sample_Size,Age(years),Education,Gender,Income,Race/Ethnicity,ClassID,QuestionID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1,Total,Data_Value
0,2011,AL,7304.0,NaN,NaN,NaN,NaN,NaN,OWS,Q036,Total,Total,OVR,OVERALL,Total,32.0
1,2011,AL,2581.0,NaN,NaN,Male,NaN,NaN,OWS,Q036,Gender,Male,GEN,MALE,NaN,32.3
2,2011,AL,4723.0,NaN,NaN,Female,NaN,NaN,OWS,Q036,Gender,Female,GEN,FEMALE,NaN,31.8
3,2011,AL,1153.0,NaN,Less than high school,NaN,NaN,NaN,OWS,Q036,Education,Less than high school,EDU,EDUHS,NaN,33.6
4,2011,AL,2402.0,NaN,High school graduate,NaN,NaN,NaN,OWS,Q036,Education,High school graduate,EDU,EDUHSGRAD,NaN,32.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53387,2016,VI,NaN,NaN,NaN,NaN,NaN,Asian,PA,Q047,Race/Ethnicity,Asian,RACE,RACEASN,NaN,NaN
53388,2016,VI,NaN,NaN,NaN,NaN,NaN,Hawaiian/Pacific Islander,PA,Q047,Race/Ethnicity,Hawaiian/Pacific Islander,RACE,RACEHPI,NaN,NaN
53389,2016,VI,NaN,NaN,NaN,NaN,NaN,American Indian/Alaska Native,PA,Q047,Race/Ethnicity,American Indian/Alaska Native,RACE,RACENAA,NaN,NaN
53390,2016,VI,NaN,NaN,NaN,NaN,NaN,2 or more races,PA,Q047,Race/Ethnicity,2 or more races,RACE,RACE2PLUS,NaN,NaN
53391,2016,VI,NaN,NaN,NaN,NaN,NaN,Other,PA,Q047,Race/Ethnicity,Other,RACE,RACEOTH,NaN,NaN

In [ ]:
df.columns = df.columns.str.lower()
df.head()

,yearend,locationabbr,sample_size,age(years),education,gender,income,race/ethnicity,classid,questionid,stratificationcategory1,stratification1,stratificationcategoryid1,stratificationid1,total,data_value
0,2011,AL,7304.0,NaN,NaN,NaN,NaN,NaN,OWS,Q036,Total,Total,OVR,OVERALL,Total,32.0
1,2011,AL,2581.0,NaN,NaN,Male,NaN,NaN,OWS,Q036,Gender,Male,GEN,MALE,NaN,32.3
2,2011,AL,4723.0,NaN,NaN,Female,NaN,NaN,OWS,Q036,Gender,Female,GEN,FEMALE,NaN,31.8
3,2011,AL,1153.0,NaN,Less than high school,NaN,NaN,NaN,OWS,Q036,Education,Less than high school,EDU,EDUHS,NaN,33.6
4,2011,AL,2402.0,NaN,High school graduate,NaN,NaN,NaN,OWS,Q036,Education,High school graduate,EDU,EDUHSGRAD,NaN,32.8